name:                serverless-haskell-sandbox
category:            AWS, Cloud, Network
maintainer:          ah@jabara.info
version:             1.0.0
github:              jabaraster/serverless-haskell-sandbox
license:             MIT
synopsis:            Deploying Haskell code onto AWS Lambda using Serverless
description:         Example package to demonstrate deployment of Haskell code onto AWS Lambda using Serverless

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - bytestring
  - uuid
  - aeson
  - unordered-containers
  - lens
  - serverless-haskell
  - http-types
  - amazonka
  - amazonka-core
  - amazonka-dynamodb
  - amazonka-s3
  - attoparsec
  - unordered-containers
  - http-client
  - http-conduit
  - directory

executables:
  env:
    main:                Main.hs
    source-dirs:         app/env
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - lens
    - serverless-haskell
    - serverless-haskell-sandbox
  hello:
    main:                Main.hs
    source-dirs:         app/hello
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - lens
    - serverless-haskell
    - serverless-haskell-sandbox
  echo:
    main:                Main.hs
    source-dirs:         app/echo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - lens
    - serverless-haskell
    - serverless-haskell-sandbox
  http:
    main:                Main.hs
    source-dirs:         app/http
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - aeson
    - bytestring
    - lens
    - serverless-haskell
    - serverless-haskell-sandbox
  postData:
    main:                Main.hs
    source-dirs:         app/postData
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - aeson
    - lens
    - serverless-haskell
    - serverless-haskell-sandbox
  getData:
    main:                Main.hs
    source-dirs:         app/getData
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens
    - HTTP
    - serverless-haskell
    - serverless-haskell-sandbox
  s3:
    main:                Main.hs
    source-dirs:         app/s3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - text
    - lens
    - serverless-haskell
    - serverless-haskell-sandbox
tests:
    dynamodb-test:
        main:        Spec.hs
        source-dirs: test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - hspec
        - unordered-containers
        - serverless-haskell
        - serverless-haskell-sandbox

