service: serverless-haskell-sandbox

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1

functions:
  hello:
    handler: serverless-haskell-sandbox.hello # <serviceの値>.<exeの名前>
    events:
      - http:
          path: hello
          method: get
  echo:
    handler: serverless-haskell-sandbox.echo
    events:
      - http:
          path: echo/{name}
          method: get

plugins:
  - serverless-haskell
