resolver: lts-12.0

packages:
- .
- ../amazonka/amazonka
- ../serverless-haskell
  # - ../amazonka/core
  # - ../amazonka/amazonka-dynamodb
  # - ../amazonka/amazonka-s3
extra-deps:
- serverless-haskell-0.8.3
